# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optionally set the version of Python and requirements required to build your docs
python:
  version: "3.12"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Optionally build docs for specific branches
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Optionally specify the conda environment file
#conda:
#  file: docs/environment.yml
